INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('AZ','Azerbaijan','azerbaijan'),
	 ('RS','Serbia','serbia'),
	 ('SV','El Salvador','el-salvador'),
	 ('GQ','Equatorial Guinea','equatorial-guinea'),
	 ('TL','Timor-Leste','timor-leste'),
	 ('VU','Vanuatu','vanuatu'),
	 ('MW','Malawi','malawi'),
	 ('PS','Palestinian Territory','palestine'),
	 ('AO','Angola','angola'),
	 ('GU','Guam','guam');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('MO','Macao, SAR China','macao-sar-china'),
	 ('MN','Mongolia','mongolia'),
	 ('SM','San Marino','san-marino'),
	 ('BJ','Benin','benin'),
	 ('EE','Estonia','estonia'),
	 ('MK','Macedonia, Republic of','macedonia'),
	 ('FM','Micronesia, Federated States of','micronesia'),
	 ('NE','Niger','niger'),
	 ('SR','Suriname','suriname'),
	 ('DJ','Djibouti','djibouti');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('EC','Ecuador','ecuador'),
	 ('GA','Gabon','gabon'),
	 ('KN','Saint Kitts and Nevis','saint-kitts-and-nevis'),
	 ('ZA','South Africa','south-africa'),
	 ('BD','Bangladesh','bangladesh'),
	 ('SG','Singapore','singapore'),
	 ('UZ','Uzbekistan','uzbekistan'),
	 ('BG','Bulgaria','bulgaria'),
	 ('CL','Chile','chile'),
	 ('CG','Congo (Brazzaville)','congo-brazzaville');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('FO','Faroe Islands','faroe-islands'),
	 ('PF','French Polynesia','french-polynesia'),
	 ('TF','French Southern Territories','french-southern-territories'),
	 ('MZ','Mozambique','mozambique'),
	 ('NI','Nicaragua','nicaragua'),
	 ('ZW','Zimbabwe','zimbabwe'),
	 ('PA','Panama','panama'),
	 ('TH','Thailand','thailand'),
	 ('NG','Nigeria','nigeria'),
	 ('CO','Colombia','colombia');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('IL','Israel','israel'),
	 ('TJ','Tajikistan','tajikistan'),
	 ('TG','Togo','togo'),
	 ('ET','Ethiopia','ethiopia'),
	 ('PY','Paraguay','paraguay'),
	 ('SS','South Sudan','south-sudan'),
	 ('MV','Maldives','maldives'),
	 ('AE','United Arab Emirates','united-arab-emirates'),
	 ('EH','Western Sahara','western-sahara'),
	 ('BT','Bhutan','bhutan');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('GP','Guadeloupe','guadeloupe'),
	 ('MH','Marshall Islands','marshall-islands'),
	 ('ME','Montenegro','montenegro'),
	 ('NR','Nauru','nauru'),
	 ('DK','Denmark','denmark'),
	 ('IR','Iran, Islamic Republic of','iran'),
	 ('KW','Kuwait','kuwait'),
	 ('SO','Somalia','somalia'),
	 ('BA','Bosnia and Herzegovina','bosnia-and-herzegovina'),
	 ('BI','Burundi','burundi');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('FJ','Fiji','fiji'),
	 ('QA','Qatar','qatar'),
	 ('CH','Switzerland','switzerland'),
	 ('AI','Anguilla','anguilla'),
	 ('KE','Kenya','kenya'),
	 ('MT','Malta','malta'),
	 ('NP','Nepal','nepal'),
	 ('OM','Oman','oman'),
	 ('AX','ALA Aland Islands','ala-aland-islands'),
	 ('BF','Burkina Faso','burkina-faso');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('XK','Republic of Kosovo','kosovo'),
	 ('TO','Tonga','tonga'),
	 ('CD','Congo (Kinshasa)','congo-kinshasa'),
	 ('DO','Dominican Republic','dominican-republic'),
	 ('HN','Honduras','honduras'),
	 ('IS','Iceland','iceland'),
	 ('PE','Peru','peru'),
	 ('GS','South Georgia and the South Sandwich Islands','south-georgia-and-the-south-sandwich-islands'),
	 ('BZ','Belize','belize'),
	 ('IO','British Indian Ocean Territory','british-indian-ocean-territory');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('SA','Saudi Arabia','saudi-arabia'),
	 ('US','United States of America','united-states'),
	 ('GH','Ghana','ghana'),
	 ('YT','Mayotte','mayotte'),
	 ('MF','Saint-Martin (French part)','saint-martin-french-part'),
	 ('VI','Virgin Islands, US','virgin-islands'),
	 ('KH','Cambodia','cambodia'),
	 ('CU','Cuba','cuba'),
	 ('NZ','New Zealand','new-zealand'),
	 ('BR','Brazil','brazil');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('BL','Saint-Barthélemy','saint-barthélemy'),
	 ('WS','Samoa','samoa'),
	 ('CI','Côte d''Ivoire','cote-divoire'),
	 ('SC','Seychelles','seychelles'),
	 ('UY','Uruguay','uruguay'),
	 ('IT','Italy','italy'),
	 ('MM','Myanmar','myanmar'),
	 ('LC','Saint Lucia','saint-lucia'),
	 ('VG','British Virgin Islands','british-virgin-islands'),
	 ('FK','Falkland Islands (Malvinas)','falkland-islands-malvinas');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('HU','Hungary','hungary'),
	 ('KR','Korea (South)','korea-south'),
	 ('MG','Madagascar','madagascar'),
	 ('DM','Dominica','dominica'),
	 ('GF','French Guiana','french-guiana'),
	 ('GM','Gambia','gambia'),
	 ('JE','Jersey','jersey'),
	 ('MX','Mexico','mexico'),
	 ('LK','Sri Lanka','sri-lanka'),
	 ('LU','Luxembourg','luxembourg');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('DZ','Algeria','algeria'),
	 ('AW','Aruba','aruba'),
	 ('MS','Montserrat','montserrat'),
	 ('MP','Northern Mariana Islands','northern-mariana-islands'),
	 ('TW','Taiwan, Republic of China','taiwan'),
	 ('AS','American Samoa','american-samoa'),
	 ('AD','Andorra','andorra'),
	 ('KM','Comoros','comoros'),
	 ('NO','Norway','norway'),
	 ('AR','Argentina','argentina');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('AT','Austria','austria'),
	 ('IM','Isle of Man','isle-of-man'),
	 ('LR','Liberia','liberia'),
	 ('SZ','Swaziland','swaziland'),
	 ('HR','Croatia','croatia'),
	 ('GW','Guinea-Bissau','guinea-bissau'),
	 ('MQ','Martinique','martinique'),
	 ('AQ','Antarctica','antarctica'),
	 ('AU','Australia','australia'),
	 ('BS','Bahamas','bahamas');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('FI','Finland','finland'),
	 ('ID','Indonesia','indonesia'),
	 ('JP','Japan','japan'),
	 ('LV','Latvia','latvia'),
	 ('TK','Tokelau','tokelau'),
	 ('AM','Armenia','armenia'),
	 ('CA','Canada','canada'),
	 ('HK','Hong Kong, SAR China','hong-kong-sar-china'),
	 ('BO','Bolivia','bolivia'),
	 ('GN','Guinea','guinea');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('KG','Kyrgyzstan','kyrgyzstan'),
	 ('NF','Norfolk Island','norfolk-island'),
	 ('PK','Pakistan','pakistan'),
	 ('SL','Sierra Leone','sierra-leone'),
	 ('KY','Cayman Islands','cayman-islands'),
	 ('GE','Georgia','georgia'),
	 ('HM','Heard and Mcdonald Islands','heard-and-mcdonald-islands'),
	 ('WF','Wallis and Futuna Islands','wallis-and-futuna-islands'),
	 ('FR','France','france'),
	 ('JM','Jamaica','jamaica');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('PG','Papua New Guinea','papua-new-guinea'),
	 ('AF','Afghanistan','afghanistan'),
	 ('BV','Bouvet Island','bouvet-island'),
	 ('CR','Costa Rica','costa-rica'),
	 ('EG','Egypt','egypt'),
	 ('KZ','Kazakhstan','kazakhstan'),
	 ('MD','Moldova','moldova'),
	 ('TZ','Tanzania, United Republic of','tanzania'),
	 ('TV','Tuvalu','tuvalu'),
	 ('UM','US Minor Outlying Islands','us-minor-outlying-islands');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('VN','Viet Nam','vietnam'),
	 ('BB','Barbados','barbados'),
	 ('GT','Guatemala','guatemala'),
	 ('ES','Spain','spain'),
	 ('UG','Uganda','uganda'),
	 ('YE','Yemen','yemen'),
	 ('CM','Cameroon','cameroon'),
	 ('VA','Holy See (Vatican City State)','holy-see-vatican-city-state'),
	 ('MR','Mauritania','mauritania'),
	 ('IN','India','india');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('NU','Niue','niue'),
	 ('AG','Antigua and Barbuda','antigua-and-barbuda'),
	 ('SB','Solomon Islands','solomon-islands'),
	 ('TC','Turks and Caicos Islands','turks-and-caicos-islands'),
	 ('GL','Greenland','greenland'),
	 ('LB','Lebanon','lebanon'),
	 ('BW','Botswana','botswana'),
	 ('TD','Chad','chad'),
	 ('CY','Cyprus','cyprus'),
	 ('GD','Grenada','grenada');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('HT','Haiti','haiti'),
	 ('MU','Mauritius','mauritius'),
	 ('AN','Netherlands Antilles','netherlands-antilles'),
	 ('PW','Palau','palau'),
	 ('SJ','Svalbard and Jan Mayen Islands','svalbard-and-jan-mayen-islands'),
	 ('SE','Sweden','sweden'),
	 ('DE','Germany','germany'),
	 ('LA','Lao PDR','lao-pdr'),
	 ('RU','Russian Federation','russia'),
	 ('SN','Senegal','senegal');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('BN','Brunei Darussalam','brunei'),
	 ('IE','Ireland','ireland'),
	 ('KI','Kiribati','kiribati'),
	 ('PT','Portugal','portugal'),
	 ('RO','Romania','romania'),
	 ('RW','Rwanda','rwanda'),
	 ('TN','Tunisia','tunisia'),
	 ('KP','Korea (North)','korea-north'),
	 ('LT','Lithuania','lithuania'),
	 ('NA','Namibia','namibia');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('PL','Poland','poland'),
	 ('VE','Venezuela (Bolivarian Republic)','venezuela'),
	 ('CZ','Czech Republic','czech-republic'),
	 ('TT','Trinidad and Tobago','trinidad-and-tobago'),
	 ('UA','Ukraine','ukraine'),
	 ('BH','Bahrain','bahrain'),
	 ('CX','Christmas Island','christmas-island'),
	 ('MA','Morocco','morocco'),
	 ('PH','Philippines','philippines'),
	 ('PR','Puerto Rico','puerto-rico');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('SH','Saint Helena','saint-helena'),
	 ('VC','Saint Vincent and Grenadines','saint-vincent-and-the-grenadines'),
	 ('BY','Belarus','belarus'),
	 ('CV','Cape Verde','cape-verde'),
	 ('GG','Guernsey','guernsey'),
	 ('CC','Cocos (Keeling) Islands','cocos-keeling-islands'),
	 ('PN','Pitcairn','pitcairn'),
	 ('RE','Réunion','réunion'),
	 ('SI','Slovenia','slovenia'),
	 ('SY','Syrian Arab Republic (Syria)','syria');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('AL','Albania','albania'),
	 ('MC','Monaco','monaco'),
	 ('SK','Slovakia','slovakia'),
	 ('BM','Bermuda','bermuda'),
	 ('CF','Central African Republic','central-african-republic'),
	 ('GY','Guyana','guyana'),
	 ('LY','Libya','libya'),
	 ('ML','Mali','mali'),
	 ('ER','Eritrea','eritrea'),
	 ('LS','Lesotho','lesotho');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('NC','New Caledonia','new-caledonia'),
	 ('CN','China','china'),
	 ('CK','Cook Islands','cook-islands'),
	 ('JO','Jordan','jordan'),
	 ('MY','Malaysia','malaysia'),
	 ('PM','Saint Pierre and Miquelon','saint-pierre-and-miquelon'),
	 ('TM','Turkmenistan','turkmenistan'),
	 ('ZM','Zambia','zambia'),
	 ('GR','Greece','greece'),
	 ('IQ','Iraq','iraq');
INSERT INTO public.country (countrycode,countryname,countryslug) VALUES
	 ('BE','Belgium','belgium'),
	 ('GI','Gibraltar','gibraltar'),
	 ('TR','Turkey','turkey'),
	 ('GB','United Kingdom','united-kingdom'),
	 ('LI','Liechtenstein','liechtenstein'),
	 ('NL','Netherlands','netherlands'),
	 ('ST','Sao Tome and Principe','sao-tome-and-principe'),
	 ('SD','Sudan','sudan');